### ISSUE TITLE
Change browser to Chromium

### ISSUE THREAD

**Issue by 5nacks** [tracelabs/tlosint-live#46]
Browser change to Chromium due to issues with the searchparty website and chromium is now providing better compatibility across the board.

**Todo:**
- [X] Add the Chromium browser ;
- [X] Add security policies ;
- [X] Import default bookmarks (see https://github.com/5nacks/OSINTBookmarks) ;
- [X] Setup hardening configuration.

**Comment by charlescebe** [comment]
Issue solved in PR https://github.com/tracelabs/tlosint-live/pull/57.
