### ISSUE TITLE
[Tool request] tiktok-scraper

### ISSUE THREAD

**Issue by Sp8c3** [tracelabs/tlosint-live#58]
Hey, I found this great tool for scraping information from TikTok which is very popular these days, but it's very hard to extract data by normal means so I think it should be added to the VM

[github.com/drawrowfly/tiktok-scraper](https://github.com/drawrowfly/tiktok-scraper)

**Todo:**

- [X] update `kali.list.chroot`, add `nodejs` and `npm` packages in pre-reqs
- [X] update `osint-packages.chroot` add `tiktok-scraper`
- [X] add `tiktok-scraper` launcher helper script in `/usr/bin/ folder
- [X] add `.desktop` file for `tiktop-scraper` tool
- [X] update the `update.sh` script: update `npm` to latest version as well as all npm package globally
- [X] update `README.md` file

**Comment by 5nacks** [comment]
Hi - Great suggestion, we will review the tool and look at adding it in assuming it works correctly 👍

**Comment by m0st4sh** [comment]
Issue solved in PR https://github.com/tracelabs/tlosint-live/pull/59.
