### ISSUE TITLE
[Tool request] onionsearch

### ISSUE THREAD

**Issue by 5nacks** [tracelabs/tlosint-live#66]
**Is your feature request related to a problem? Please describe.**
We don't have many darkweb tools

**Describe the tool you'd like**
automate searching the dark web

**A link to the tool**
https://github.com/megadose/OnionSearch

**Additional context**

**Todo:**
- [X] update `osint-packages.chroot`, add `OnionSearch`
- [X] add `OnionSearch` launch helper script
- [X] add `OnionSearch` desktop file
- [X] update `update.sh` script for OnionSearch
- [X] update `README.md`

**Comment by m0st4sh** [comment]
**Tool added in PR:** https://github.com/tracelabs/tlosint-live/pull/67
